# Generated by Django 5.0.2 on 2024-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='trade_code',
            field=models.CharField(max_length=100),
        ),
    ]
